data:
  asset_type: glass-insulator
  augmentation: null
  batch_size: 32
  dataset: InsPLAD
  transform: resnet18
logger:
  entity: atticux
  project: STPFM-v2
  run_name: resnet18-stpfmv2-glass-insulator
  # run_name: test_run
model:
  backbone: resnet18
  name: STPFMv2
optimizer:
  lr: 0.001
  name: adam
training:
  max_epochs: 100
