data:
  asset_type: glass-insulator
  augmentation: null
  batch_size: 32
  dataset: InsPLAD
  transform: imagenet
logger:
  entity: atticux
  project: STPFM-v2
  run_name: stpfmv2-glass-insulator-resnet18
  # run_name: test_run_phard0.9_mean_forward
model:
  backbone: resnet18
  name: STPFMv2
optimizer:
  lr: 0.5
  name: adam
training:
  max_epochs: 100
