data:
  asset_type: damper-preformed
  augmentation: null
  batch_size: 4
  dataset: InsPLAD
  transform: imagenet
logger:
  entity: atticux
  project: STPFM-v2
  run_name: test_run
model:
  backbone: resnet18
  name: STPFM
optimizer:
  lr: 0.4
  name: adam
training:
  max_epochs: 100
