data:
  asset_type: glass-insulator
  augmentation: null
  batch_size: 32
  dataset: InsPLAD
  transform: resnet18
logger:
  entity: atticux
  project: STPFM-v2
  run_name: stpfm-glass-insulator-resnet18
  # run_name: test_run
model:
  backbone: resnet18
  name: STPFM
optimizer:
  lr: 0.5
  name: adam
training:
  max_epochs: 100
