data:
  asset_type: glass-insulator
  augmentation: null
  batch_size: 32
  dataset: InsPLAD
  transform: resnet18_256
logger:
  entity: atticux
  project: STPFM-InsPLAD
  run_name: wide_resnet101_2-stpfm-glass-insulator
  # run_name: test_run_phard0.9_mean_forward
model:
  backbone: wide_resnet101_2
  name: STPFM
optimizer:
  lr: 0.01
  name: adam
training:
  max_epochs: 100
